name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./HMS SYSTEM  # Set the context to the folder containing your Dockerfile
          file: ./HMS SYSTEM/Dockerfile  # the path to your Dockerfile
          push: true
          tags: 37833707/nwu-hms:latest  # Your Docker Hub username

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: NWU-HMS
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 37833707/nwu-hms:latest
